### ISSUE TITLE
Actions 运行出错

### ISSUE THREAD

**Issue by Hashcoel** [NollGo/Noll#30]
错误日志：chmod: cannot access './GitHub-Discussions-to-Blog/io.github.topages': No such file or directory

**Comment by excing** [comment]
你好，请复制下面 `noll.yml` 的内容到你仓库的 `.github/workflow/noll.yml` 文件里，然后重新发布一个 Discusions 试试。

<https://github.com/NollGo/NollAction/blob/main/.github/workflows/noll.yml>
