### ISSUE TITLE
模板后缀能不能改成 .gohtml

### ISSUE THREAD

**Issue by fzdwx** [NollGo/Noll#40]
配合 idea (Go templates) 有类型提示

![image](https://user-images.githubusercontent.com/65269574/222036306-51de902c-855c-4538-a066-c1b827bd781d.png)

**Comment by excing** [comment]
你好，你可以在 IDEA 里通过以下步骤为特定后缀名的文件设置语言：

- 打开 IntelliJ IDEA 并导航到 "File" > "Settings"。
- 在弹出的窗口中，选择 "Editor" > "File Types"。
- 在 "File Types" 窗格中，选择您想要更改的文件类型（例如，"Text"）。
- 在 "File name Patterns" 窗格中，单击 "Add" 按钮，并输入您想要更改语言的文件后缀名（例如，"*.gohtml"）。
